<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<h1><?php echo $this->translate("Import a game"); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="label-input">
            <?php echo $this->translate("Put a Slug if you want to change it")?>
            <?php echo $this->formLabel($form->get('slug')); ?>
            <?php echo $this->formInput($form->get('slug')); ?>
            <?php echo $this->formElementErrors($form->get('slug')) ?>
    	</div>
        <div class="label-input">
            <?php echo $this->formLabel($form->get('import_file')); ?>
            <?php echo $this->formFile($form->get('import_file')); ?>
            <?php echo $this->formElementErrors($form->get('import_file')) ?>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
