<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<div class="span4">
	
	<!-- ADSERVING SIDEBAR -->
	<div id="ad-sidebar" class="sidebar-block">
		<img src="<?php echo $this->basePath('images/adserving/adserving-sidebar-menudujour.jpg')?>" width="300" height="250" border="0" />
	</div>
	<!-- END ADSERVING SIDEBAR -->
	
	<!-- sidebar random game -->
	<div class="row-fluid">
		<div id="sidebar-quiz" class="span9 center">
			<p class="green"><?php echo $this->translate('Comment participer ?'); ?></p>
			<div id="reply" class="row-fluid">
				<div class="span2">
					<img src="<?php echo $this->basePath('images/common/btn-reply.png') ?>" alt="" />
				</div>
				<div class="span10">
					<p>Cliquez sur participer</p>
				</div>
			</div>
			<div id="quiz-question" class="row-fluid">
				<div class="span2">
					<img src="<?php echo $this->basePath('images/common/btn-photo.png') ?>" alt="" />
				</div>
				<div class="span10">
					<p>Postez vos photos</p>
				</div>
			</div>
			<div id="ecusson" class="row-fluid">
				<div class="span2">
					<img src="<?php echo $this->basePath('images/common/btn-ecusson.png') ?>" alt="" />
				</div>
				<div class="span10">
					<p>Invitez vos amis à venir voter pour vous !</p>
				</div>
			</div>
		</div>
	</div>

</div>