<?php
return array(
    'modules' => array(
        'Zend\Db',
        'Zend\Log',
        'Zend\Mail',
        'Zend\Serializer',
        'Zend\Cache',
        'Zend\Mvc\Console',
        'Zend\Mvc\Plugin\FilePrg',
        'Zend\ServiceManager\Di',
        'Zend\Router',
        'Zend\Navigation',
        'Zend\I18n',
        'Zend\Mvc\I18n',
        'Zend\Paginator',
        'Zend\Session',
        'Zend\Form',
        'Zend\InputFilter',
        'Zend\Filter',
        'Zend\Hydrator',
        'Zend\Router',
        'Zend\Validator',
        'Zend\Mvc\Plugin\FlashMessenger',
        //'Zend\Mvc\Plugin\Identity',
        'Zend\Mvc\Plugin\Prg',
        'DoctrineModule',
        'DoctrineORMModule',
        'DoctrineDataFixtureModule',
        'PlaygroundCore',
        'PlaygroundDesign',
        'PlaygroundUser',
        'PlaygroundGame',
        'PlaygroundPartnership'
    ),
    'module_listener_options' => array(
        'config_glob_paths'    => array(
            '../../../config/autoload/{,*.}{global,local,testing}.php',
            './config/{,*.}{testing}.php',
        ),
        'module_paths' => array(
            'module',
            'vendor',
        ),
    ),
);
