<?php
return array(
    'modules' => array(
        'Laminas\Db',
        'Laminas\Log',
        'Laminas\Mail',
        'Laminas\Serializer',
        'Laminas\Cache',
        'Laminas\Mvc\Console',
        'Laminas\Mvc\Plugin\FilePrg',
        'Laminas\ServiceManager\Di',
        'Laminas\Router',
        'Laminas\Navigation',
        'Laminas\I18n',
        'Laminas\Mvc\I18n',
        'Laminas\Paginator',
        'Laminas\Session',
        'Laminas\Form',
        'Laminas\InputFilter',
        'Laminas\Filter',
        'Laminas\Hydrator',
        'Laminas\Router',
        'Laminas\Validator',
        'Laminas\Mvc\Plugin\FlashMessenger',
        //'Laminas\Mvc\Plugin\Identity',
        'Laminas\Mvc\Plugin\Prg',
        'DoctrineModule',
        'DoctrineORMModule',
        'DoctrineDataFixtureModule',
        'PlaygroundCore',
        'PlaygroundDesign',
        'ZfcUser',
        'PlaygroundUser',
        'PlaygroundGame',
        'PlaygroundPartnership'
    ),
    'module_listener_options' => array(
        'config_glob_paths'    => array(
            '../../../config/autoload/{,*.}{global,local,testing}.php',
            './config/{,*.}{testing}.php',
        ),
        'module_paths' => array(
            'module',
            'vendor',
        ),
    ),
);
