<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $game = $this->game;?>
<?php $user = $this->user;?>
<?php $availableGames = $this->availableGames?>

<div class="game-postvote row-fluid recirculation">
	
	<!-- BUTTONS -->
	<div class="row-fluid buttons">
		<div class="span2">
			<a href="<?php echo $this->url('postvote', array('id' => $this->game->getIdentifier()))?>"><button class="btn btn-inverse active">Accueil</button></a>
		</div>
		<div class="span4">
			<a href="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode()))?>"><button class="btn btn-inverse">Voir les participations</button></a>
		</div>
		<div class="span3">
			<a href="<?php echo $this->url('postvote/play', array('id' => $this->game->getIdentifier()))?>"><button class="btn btn-warning">Participer</button></a>
		</div>
	</div>
	
	<div class="row-fluid sep"><img src="<?php echo $this->frontendAssetPath('images/common/sep-horizontal.jpg')?>" width="620" height="15" border="0"/></div>
	
	<!-- BOUNCE -->
	<?php echo $this->partial('playground-game/partial/bounce', array(
		'game' => $game,
		'user' => $user,
		'gameType' => 'Ce post &amp; vote',
		'channel' => $this->channel,
		'isSubscriber' => $this->partnerSubscriber($game->getPartner(), $user) )
	);?>
	
	<!-- OTHER GAMES -->
	<?php if($this->channel === ''){?>
	<div class="row-fluid other-games">
		<h2 class="title">
			<?php if($availableGames): ?>
				<?php echo $this->translate('Tentez votre chance avec d\'autres jeux'); ?> Club Playground
			<?php else: ?>
				<?php echo $this->translate('Vous avez joué à tous les jeux'); ?> ! <br/>
				<?php echo $this->translate('Revenez très bientôt'); ?>
			<?php endif; ?>
		</h2>
		<?php $this->partialLoop()->setObjectKey('game')?>
		<?php echo $this->partialLoop('playground-game/partial/game.phtml', $availableGames) ?>
	</div>
	<?php } ?>
	
	<!-- RSS FEED -->
	<?php echo $this->partial('playground-game/partial/news-feed', array('rssUrl' => $this->rssUrl)); ?>

</div>