<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="span4 mobile sidebar game-sidebar">
	<div class="row-fluid">
		<?php if(($this->dynablockWidget('game'.$this->game->getId())) != ''):?>
	    	<?php foreach($this->dynablockWidget('game'.$this->game->getId()) as $block): ?>
	    		<div class="sd-block ad"><?php echo $block ?></div>
	    	<?php endforeach; ?>
    	<?php endif; ?>
	
		<div id="sidebar-game" class="sd-block">
			<p class="green"><?php echo $this->translate('Comment participer ?'); ?></p>
			<div id="reply" class="row-fluid">
				<div class="span2">
					<img src="<?php echo $this->basePath('images/common/btn-reply.png') ?>" alt="" />
				</div>
				<div class="span10">
					<p>Cliquez sur participer</p>
				</div>
			</div>
			<div id="quiz-question" class="row-fluid">
				<div class="span2">
					<img src="<?php echo $this->basePath('images/common/btn-edit.png') ?>" alt="" />
				</div>
				<div class="span10">
					<p>Rédiger votre message</p>
				</div>
			</div>
			<div id="ecusson" class="row-fluid">
				<div class="span2">
					<img src="<?php echo $this->basePath('images/common/btn-parrain.png') ?>" alt="" />
				</div>
				<div class="span10">
					<p>Invitez vos amis à venir voter pour vous !</p>
				</div>
			</div>
		</div>
	</div>
</div>