<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="game-postvote row-fluid welcome">
	<h1><?php echo $this->game->getTitle(); ?></h1>

	<!-- BLOCK GAME START -->
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game));?>
    <!-- END BLOCK GAME START -->

	<!-- contenu article -->
	<div id="content-article" class="row-fluid rounded backgrey">

		<?php if(count($this->flashMessages)>0):?>
			<p class="already-play"><?php echo $this->flashMessages[0];?></p>
	    <?php endif;?>

		<div class="welcome-block<?php if($this->channel === 'facebook'): echo ' fb-target'; endif ?>"><?php echo $this->game->getWelcomeBlock(); ?></div>
		<div class="center">
			<div class="btn btn-inverse seeparticipants">
				<a href="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode()))?>" class="arrow-right">Voir les participants</a>
			</div>
			<?php if($game->isStarted()):?>
			<div class="btn btn-warning"<?php if ($this->isCtaActive) { echo ' id="fb-play"'; } ?>>
				<a href="<?php echo $this->url('postvote/play', array('id' => $this->game->getIdentifier()))?>" class="arrow-right">Participer</a>
			</div>
			<?php endif;?>
		</div>
	</div>
    <p id="conditions"><a href="<?php echo $this->url('postvote/conditions', array('id' => $this->game->getIdentifier()))?>" target="_blank">Mentions légales</a></p>
	<p id="reglement"><a href="<?php echo $this->url('postvote/terms', array('id' => $this->game->getIdentifier()))?>" target="_blank">Règlement</a></p>
</div>