<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="game-postvote list row-fluid">
	<h1><?php echo $this->game->getTitle(); ?></h1>
	<!-- BLOCK GAME START -->
	<div class="block-game game-play">
		<div class="img-content">
			<img class="rounded" src="<?php echo $this->basePath($this->game->getSecondImage()); ?>" border="0" />

			<?php if($this->game->getPartner()):?>
				<?php if( ($this->game->getPartner()->getLogo() != '')) : ?>
					<div class="logo-sponsor">
						<img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" width="120" border="0" alt="<?php echo $this->game->getPartner()->getName();?>" />
					</div>
				<?php endif;?>
			<?php else :?>
				<div class="logo-sponsor">
					<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" width="83" height="81" border="0" alt="logo" />
				</div>
			<?php endif;?>

			<div class="dark-overlay row-fluid">
				<div class="postvote"><?php echo $this->translate('Post & Vote'); ?> offert par <?php if($this->game->getPartner()): echo $this->game->getPartner()->getName(); else:?>Club Playground<?php endif;?></div>
			</div>
		</div>
	</div>
	<!-- END BLOCK GAME START -->

	<!-- BLOCK CONTENT -->
    <div class="row-fluid buttons">
		<div class="span2">
			<a href="<?php echo $this->url('postvote', array('id' => $this->game->getIdentifier()))?>"><button class="btn btn-inverse active">Accueil</button></a>
		</div>
		<div class="span4">
			<a href="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode()))?>"><button class="btn btn-inverse">Voir les participations</button></a>
		</div>
		<?php if($game->isStarted()):?>
			<div class="span3">
				<a href="<?php echo $this->url('postvote/play', array('id' => $this->game->getIdentifier()))?>"><button class="btn btn-warning">Participer</button></a>
			</div>
		<?php endif ?>
	</div>

    <div class="row-fluid sep"><img src="<?php echo $this->frontendAssetPath('images/common/sep-horizontal.jpg')?>" width="620" height="15" border="0"/></div>


	<div class="row-fluid search-bar">
        <div class="span3">
            <select name="filter-postvote" id="filter-postvote">
                <option value="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => 'date'))?>"<?php if($this->filter == 'date') : echo ' selected'; endif; ?>>Plus récents</option>
                <option value="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => 'random'))?>"<?php if($this->filter == 'random') : echo ' selected'; endif; ?>>Aléatoire</option>
                <option value="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => 'vote'))?>"<?php if($this->filter == 'vote') : echo ' selected'; endif; ?>>Plus populaires</option>
            </select>
        </div>
        <form action="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->filter)); ?>" method="GET" class="row-fluid">
	        <div class="span4 offset4">	            
				<input type="text" name="name" id="" placeholder="Rechercher" value="<?php echo $this->search?>"/>
	        </div>
	        <div class="span1 btn-search">
	            <input type="submit" class="btn btn-success" value="rechercher" />
	            <img  class="btn-glass" src="<?php echo $this->frontendAssetPath('images/common/btn-glass.png')?>" alt="" width="16" height="17"/>
	        </div>
        </form>
    </div>

	<?php echo $this->paginationControl($this->posts, 'Sliding', 'playground-game/postvote/pagination_list.phtml', array('id' => $this->game->getIdentifier(), 'filter' => $this->filter)); ?>
	
	<?php $form = $this->form;?>
	<?php $form->prepare();?>

	<?php //echo ($this->statusMail)? 'Mail envoyé': ''  ?>
	<div class="row-fluid posts consultation-list-wrap<?php if(!$game->isStarted()):?> game-close<?php endif ?>">
			<?php foreach($this->posts as $post): ?>
				<div class="row-fluid">
					<div class="span10 rounded">
						
						<?php if($this->game->getTemplate() == 'photo'): ?>
							
							<div class="photo-noslider">
								<?php if(isset($post['data'][1])):?>
									<h2 class="green"><a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><?php echo $post['data'][1];?></a></h2>
								<?php endif ?>
							    <div class="couv-img">
							    	<?php if(isset($post['data'][2])):?>
							    		<a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><img src="<?php echo $this->basePath($post['data'][2])?>" alt="" /></a>
							    	<?php elseif(isset($post['data'][3])):?>
							    		<a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><img src="<?php echo $this->basePath($post['data'][3])?>" alt="" /></a>
							    	<?php elseif(isset($post['data'][4])):?>
							    		<a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><img src="<?php echo $this->basePath($post['data'][4])?>" alt="" /></a>
							    	<?php elseif(isset($post['data'][5])):?>
							    		<a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><img src="<?php echo $this->basePath($post['data'][5])?>" alt="" /></a>
							    	<?php elseif(isset($post['data'][6])):?>
							    		<a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><img src="<?php echo $this->basePath($post['data'][6])?>" alt="" /></a>
							    	<?php endif;?>
							    </div>
								<p><?php if(isset($post['data'][7])): echo substr(nl2br($post['data'][7]), 0, 200); endif;?>...</p>
							</div>
							
							<?php //echo $this->partial('playground-game/post-vote/templates/' . $this->game->getTemplate(), array('data'=> $post['data'])) ?>
							
						<?php elseif($this->game->getTemplate() == 'recipe'): ?>
							
							<?php if(isset($post['data'][1])):?>
								<h2 class="green"><a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><?php echo $post['data'][1];?></a></h2>
							<?php endif ?>
							<?php if(isset($post['data'][2])):?>
								<div class="picture-kitchen">
								    <a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><img src="<?php echo $this->basePath($post['data'][2])?>" border="0" /></a>
								</div>
							<?php endif ?>
							<?php if(isset($post['data'][3])):?>
								<h3 class="green">Ingrédients</h3>
								<p><?php echo substr(nl2br($post['data'][3]), 0, 200); ?>...</p>
							<?php elseif(isset($post['data'][4])):?>
								<h3 class="green">Préparation</h3>
								<p><?php echo substr(nl2br($post['data'][4]), 0, 200); ?>...</p>
							<?php elseif(isset($post['data'][5])): ?>
								<h3 class="green">Service</h3>
								<p><?php echo substr(nl2br($post['data'][5]), 0, 200); ?>...</p>
							<?php endif ?>
						
						<?php else : ?>
							
							<h2 class="green"><a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>"><?php echo $post['data'][1] ?></a></h2>
							<p class="text"><?php echo substr(nl2br($post['data'][2]), 0, 200); ?>...</p>
							
						<?php endif; ?>
						
						<p class="readmore postvote">> <a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id'])) ?>">Lire la suite</a></p>
						
						<?php echo $this->partial('playground-game/partial/name.phtml', array('post'=> $post['user'], 'game' => $game, 'urlPost' => $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']), array('force_canonical' => true)), 'postTitle' => $post['data'][1])) ?>
						
						<?php if($game->isStarted()):?>
							<?php if($this->statusMail && ($post['id'] == $this->reportId )) : ?>
								<p class="report-result">Merci d'avoir signalé.</p>
							<?php else : ?>
								<?php echo $this->form()->openTag($form) ?>
									<?php echo $this->formInput($form->get('moderation')); ?>
									<input type="hidden" name="link" value="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>" />
									<input type="hidden" name="reportid" value="<?php echo $post['id'] ?>" />
									<p class="alert-link"><a href="#">Signaler</a></p>
								<?php echo $this->form()->closeTag($form) ?>
							<?php endif; ?>
						<?php endif ?>
						
					</div>
					
					<?php if($game->isStarted()):?>
					<div class="span2">				    
				        <div class="nb-votes">
				        	<div class="already-voted">Vous avez déjà voté!</div>
				        <?php if(!$this->zfcUserIdentity()): ?>
				            <a href="<?php echo $this->url('postvote/post', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>" class="btn-post-vote"></a>
				        <?php else:?>
				            <a href="<?php echo $this->url('postvote/vote', array('id' => $this->game->getIdentifier(), 'post' => $post['id']))?>" class="btn-post-vote logged"></a>
				        <?php endif;?>
				            <div class="bn-votes"><span class="nb-post-vote-number"><?php echo $post['votes'];?></span> <?php echo ($post['votes'] > 1) ? 'votes' : 'vote'; ?></div>
				        </div>
					</div>
					<?php endif ?>
			   </div>
			<?php endforeach; ?>
	 </div>


	<?php echo $this->paginationControl($this->posts, 'Sliding', 'playground-game/postvote/pagination_list.phtml', array('id' => $this->game->getIdentifier(), 'filter' => $this->filter)); ?>

</div>