<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $data = array();foreach($this->post->getPostElements() as $element):?>
<?php $data[$element->getPosition()] = $element->getValue();?>
<?php endforeach;?>
<div class="game-postvote preview row-fluid">
	<h1><?php echo $this->game->getTitle(); ?></h1>
	<!-- BLOCK GAME START -->
	<!--
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game));?>
   -->
   <!-- BLOCK GAME START -->
	<div class="block-game game-play">
		<div class="img-content">
			<img class="rounded" src="<?php echo $this->basePath($this->game->getSecondImage()); ?>" border="0" />
			
			<?php if($this->game->getPartner()):?>
				<?php if( ($this->game->getPartner()->getLogo() != '')) : ?>
					<div class="logo-sponsor">
						<img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" width="120" border="0" alt="<?php echo $this->game->getPartner()->getName();?>" />
					</div>
				<?php endif;?>
			<?php else :?>
				<div class="logo-sponsor">		
					<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" width="83" height="81" border="0" alt="logo" />
				</div>
			<?php endif;?>
			
			<div class="dark-overlay row-fluid">
				<div class="postvote"><?php echo $this->translate('Post & Vote'); ?> offert par <?php if($this->game->getPartner()): echo $this->game->getPartner()->getName(); else:?>Club Playground<?php endif;?></div>
			</div>
		</div>
	</div>
	<!-- END BLOCK GAME START -->
   
    <!-- BLOCK CONTENT -->
    <div class="row-fluid buttons">
		<div class="span2">
			<a href="<?php echo $this->url('postvote', array('id' => $this->game->getIdentifier()))?>"><button class="btn btn-inverse active">Accueil</button></a>
		</div>
		<div class="span4">
			<a href="<?php echo $this->url('postvote/list', array('id' => $this->game->getIdentifier(), 'filter' => $this->game->getPostDisplayMode()))?>"><button class="btn btn-inverse">Voir les participations</button></a>
		</div>
		<div class="span3">
			<a href="<?php echo $this->url('postvote/play', array('id' => $this->game->getIdentifier()))?>"><button class="btn btn-warning">Participer</button></a>
		</div>
	</div>

    <!-- BLOCK CONTENT -->
   <form action="" method="post" name="preview_form">
   <div id="content-article" class="row-fluid rounded backgrey">
        <h2 class="green">Aperçu de votre message</h2>
        <p><?php echo $this->game->getForm()->getDescription(); ?></p>
       <div class="span11 message rounded">
           <div class="row-fluid posts">
				<div class="span12 postvote-preview">
               		<?php echo $this->partial('playground-game/post-vote/templates/' . $this->game->getTemplate(), array('data'=>$data, 'post'=>$this->post));?>
					<?php //echo $this->partial('playground-game/partial/name.phtml', array('post' => $this->post->getUser(), 'game' => $this->game));?>
					
					<div class="row-fluid">
					    <div class="avatar span5">
					    	<?php if($this->post->getUser()->getAvatar()):?>
						        <img src="<?php echo $this->basePath($this->post->getUser()->getAvatar()) ?>" width="24" height="24" alt="<?php echo $this->post->getUser()->getFirstname(); ?> <?php echo $this->post->getUser()->getLastname(); ?>" />
						    <?php else:?>
						    		<?php if($this->post->getUser()->getTitle() && $this->post->getUser()->getTitle() == 'M'): ?>
						        		<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-h.png'); ?>" alt="no avatar" width="24" height="24" />
						    		<?php else: ?>
						    			<img src="<?php echo $this->frontendAssetPath('images/user/no-avatar-small-f.png'); ?>" alt="no avatar" width="24" height="24" />
						    		<?php endif; ?>
						    <?php endif;?>
						    <?php echo $this->post->getUser()->getUsername(); ?>
					    </div>
					</div>

           		</div>
           </div>
           
       </div>

       <div class="row-fluid">
           <div class="modifier"><a href="<?php echo $this->url('postvote/play', array('id' => $this->game->getIdentifier()))?>">Modifier</a></div>
           <button type="submit" name="submitPost" value="" class="btn btn-warning"><span class="arrow-right">Valider</span></button>
       </div>
    </div>
    </form>
    <p id="reglement"><a href="<?php echo $this->url('postvote/terms', array('id' => $this->game->getIdentifier()))?>">Règlement</a></p>

</div>