<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $downloadLink = $this->url('admin/'. $this->game->getClassType() .'/download', array('gameId' => $this->game->getId()));?>
<?php
/*$fm = $this->flashMessenger()->setNamespace('playgroundgame')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}*/
?>
<h1><a href="<?php echo $this->url('admin/playgroundgame/edit-postvote', array('gameId' => $this->gameId)) ?>"><?php echo $this->game->getTitle(); ?></a></h1>

<h3><?php echo $this->translate('Liste des Participants'); ?></h3>

<a href='<?php echo $downloadLink ?>'>Export CSV</a>
<table class="table">
    <tr>
        <?php if (!$this->game->getAnonymousAllowed()) : ?>
            <th><?php echo $this->translate('Id'); ?></th>
            <th><?php echo $this->translate('Pseudo'); ?></th>
            <th><?php echo $this->translate('Nom'); ?></th>
            <th><?php echo $this->translate('Prenom'); ?></th>
            <th><?php echo $this->translate('E-mail'); ?></th>
        <?php endif;?>
        <?php $post = $this->posts->getItem(0); ?>
        <?php if ($post->getEntry()->getPlayerData()) : ?>
            <?php $entryData = json_decode($post->getEntry()->getPlayerData()); ?>
            <?php foreach ($entryData as $key => $attrib): ?>
                <td><?php echo $key;?> </td>
            <?php endforeach; ?>
        <?php endif; ?>

        <td> Social Shares</td>

        <th><?php echo $this->translate('Modération'); ?></th>
        <th><?php echo $this->translate('Pushed'); ?></th>
        <th></th>
    </tr>
    <?php foreach ($this->posts as $post): ?>
        <tr>
            <?php if (!$this->game->getAnonymousAllowed()) : ?>
                <td><?php echo $post->getUser()->getId(); ?></td>
                <td><?php echo $post->getUser()->getUsername(); ?></td>
                <td><?php echo $post->getUser()->getLastname(); ?></td>
                <td><?php echo $post->getUser()->getFirstname(); ?></td>
                <td><?php echo $post->getUser()->getEmail(); ?></td>
            <?php endif; ?>
            <?php if ($post->getEntry()->getPlayerData()) : ?>
                <?php $entryData = json_decode($post->getEntry()->getPlayerData()); ?>
                <?php foreach ($entryData as $key => $attrib): ?>
                    <td><?php if (is_array($attrib)) {echo implode(', ', $attrib); } else { echo $attrib; } ?></td>
                <?php endforeach; ?>
            <?php endif; ?>
            <td>
            <?php if ($post->getEntry()->getSocialShares()) : ?>
                <?php $socialData = json_decode($post->getEntry()->getSocialShares()); ?>
                <?php foreach ($socialData as $key => $attrib): ?>
                    <?php echo $key.': '?>
                    <?php if (is_array($attrib)) {echo implode(', ', $attrib); } else { echo $attrib; } ?>
                <?php endforeach; ?>
            <?php endif; ?>
            </td>
            <td>
            <?php if($post->getStatus() == 0): ?>
                En cours de création
            <?php elseif($post->getStatus() == 1):?>
                En attente de modération
            <?php elseif($post->getStatus() == 2):?>
                Accepté
            <?php elseif($post->getStatus() == 9):?>
                Refusé
            <?php else :?>
                Validé / Partagé
            <?php endif;?>
            </td>
            <td>
                <?php echo $this->translate($post->isPushed() ? 'Yes' : 'No')?>
            </td>
            <?php $editLink = $this->url('admin/playgroundgame/postvote-moderation-edit', array('postId' => $post->getId()));?>
            <?php $pushLink = $this->url('admin/playgroundgame/postvote-push', array('postId' => $post->getId(), 'pushed' => (int)(!$post->isPushed())));?>
            <td><a href='<?php echo $editLink ?>'><?php echo $this->translate('Moderate'); ?></a> 
            | <a href='<?php echo $pushLink ?>'><?php echo $this->translate($post->isPushed() ? 'Remove push' : 'Push'); ?></a></td>
            <td></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php echo (count($this->posts)>1)?$this->paginationControl($this->posts, 'Sliding', 'playground-game/admin/pagination_entrylist', array('classType' => $this->game->getClassType()  ,'gameId' => $this->gameId)):''; ?>