<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>

<h1><a href="<?php echo $this->url('admin/playgroundgame/edit-postvote', array('gameId' => $this->gameId)) ?>"><?php echo $this->game->getTitle(); ?></a></h1>

<h3><?php echo $this->translate('Options du post & vote'); ?></h3><br/><br/>

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span7">
        	<form action="" method="post" name="generate_form" id="generate_form">
                <div class="form_title_head">
                    <input type="hidden" name="form_namespace_placeholder" value="">
                    <input type="hidden" name="form_class_name_placeholder" value="">
                    <input type="hidden" name="form_class_placeholder" value="">
                    <input type="hidden" name="form_model_placeholder" value="">
                    <input type="hidden" name="form_id_placeholder" value="">
                    <h2 class="form_title_placeholder"><?php echo ($this->form)?$this->form->getTitle():'Titre';?></h2>
                    <p class="form_description_placeholder"><?php echo ($this->form)?$this->form->getDescription():'Description';?></p>
                    <button type="button" class="btn btn-link pull-right edit_form_properties"><?php echo $this->translate('Edit') ?></button>
                    <div style="clear: both"></div>
                </div>
                <br>
	    		<ul id="the_form"><?php echo $this->formTemplate;?></ul>
	    		<input type="hidden" name="form_jsonified" id="form_jsonified" value="">
	    		<input type="hidden" name="form_template" id="form_template" value="">
	    		<button class="btn" id="generate_form_button"><?php echo $this->translate('Generate Form') ?></button>
        	</form>
        </div>
        <?php echo $this->partial('playground-game/post-vote/form-menu', array('form'=>$this->form));?>
    </div>
</div>
<script>
// basepath global var put by Zend
var basepath='<?php echo $this->url('admin'); ?>';
</script>
