<div class="span5">
    <div class="well sidebar-nav">
        <ul class="nav nav-tabs" id="add_form_element">
			<li><a href="#tab_field" data-toggle="tab">Ajouter un champ</a></li>
			<li><a href="#tab_field_prop" data-toggle="tab">Propriétés du champ</a></li>
			<li><a href="#tab_form_prop" data-toggle="tab">Formulaire</a></li>
		</ul>
		<div class="tab-content">
		  	<div class="tab-pane active" id="tab_field">
		  		<table class="table table-hover">
		  			<tr>
		  				<td><div class="btn btn-info btn-block" id="single_line_text">Une ligne de texte</div></td>
		  			</tr>
		  			<tr>
		  				<td><div class="btn btn-info btn-block" id="line_paragraph">Paragraphe</div></td>
		  			</tr>
		  			<tr>
                        <td><div class="btn btn-info btn-block" id="line_upload">Fichier</div></td>
		  				<td></td>
		  			</tr>
		  		</table>
		  	</div>
		  	<div class="tab-pane" id="tab_field_prop">
		  		<div id="field_properties"></div>
		  	</div>
		  	<div class="tab-pane" id="tab_form_prop">
		  		<h3>Propriétés du formulaire</h3>
                <form>
                    <ul class="nav nav-list">
                        <li>
                            <label>Titre</label>
                            <input type="text" name="form_title" maxlength="255" value="<?php echo ($this->form)?$this->form->getTitle():'Titre';?>">
                        </li>
                        <li>
                            <label>Description</label>
                            <input type="text" name="form_description" maxlength="255" value="<?php echo ($this->form)?$this->form->getDescription():'Description';?>">
                        </li>
                        <li>
                            <!-- label>Form Namespace</label-->
                            <input type="hidden" name="form_namespace" maxlength="255" placeholder="ModuleName">
                        </li>
                        <li>
                            <!-- label>Form Class Name</label-->
                            <input type="hidden" name="form_class_name" maxlength="255" placeholder="NewForm">
                        </li>
                        <li>
                            <!-- label>Model Name</label-->
                            <input type="hidden" name="form_model" maxlength="255" placeholder="User">
                        </li>
                        <li>
                            <!-- label>Class</label-->
                            <input type="hidden" name="form_class" maxlength="255" placeholder="class1 class2..">
                        </li>
                        <li>
                            <!-- label>Id</label-->
                            <input type="hidden" name="form_id" maxlength="255" placeholder="custom id">
                        </li>
                        <li>
                            <button class="btn btn-primary" id="add_form_properties">Enregistrer</button>
                        </li>
                    </ul>
                </form>
		  	</div>
		</div>
    </div>
</div>