<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $validation = $this->url('admin/playgroundgame/postvote-moderation-edit', array('postId' => $post->getId(), 'status' => 'validation'));?>
<?php $rejection = $this->url('admin/playgroundgame/postvote-moderation-edit', array('postId' => $post->getId(), 'status' => 'rejection'));?>
<?php $data = array();foreach($this->post->getPostElements() as $element):?>
<?php $data[$element->getPosition()] = $element->getValue();?>
<?php endforeach;?>
<h2 class="green">Aperçu de votre message</h2>
<p><?php echo $this->game->getForm()->getDescription(); ?></p>
<div class="span12 message">
   <div class="row-fluid">
       <?php echo $this->partial('playground-game/frontend/post-vote/templates/' . $this->game->getTemplate(), array('data'=>$data));?>
   </div>
   <div>
        <a href='<?php echo $rejection ?>'><?php echo $this->translate('Reject'); ?></a>
        <a href='<?php echo $validation ?>'><?php echo $this->translate('Validate'); ?></a>
   </div>
</div>