<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('frontend/quiz/play', array('id' => $this->game->getIdentifier())));
?>


<?php $totalQuestions = count($this->questions);?>
<!-- GAME QUIZ - FERME QUESTIONS -->
<div class="game-quiz play row-fluid">
	<h1><?php echo $this->game->getTitle(); ?></h1>

	<!-- BLOCK GAME START -->
	<div class="block-game game-play">
		<div class="img-content">
			<img class="rounded" src="<?php echo $this->basePath($this->game->getSecondImage()); ?>" border="0" />
			
			<?php if($this->game->getPartner()):?>
				<?php if($this->game->getPartner()->getLogo()) : ?>
					<div class="logo-sponsor">
						<img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" border="0" alt="<?php echo $this->game->getPartner()->getName();?>" />
					</div>
				<?php endif;?>
			<?php else :?>
				<div class="logo-sponsor">		
					<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" width="83" height="81" border="0" alt="logo" />
				</div>
			<?php endif;?>
			
			<div class="dark-overlay row-fluid">
				<div class="quiz"><?php echo $this->translate('Quiz'); ?> offert par <?php if($this->game->getPartner()): echo $this->game->getPartner()->getName(); else:?>Club Playground<?php endif;?></div>
			</div>
		</div>
	</div><!-- END BLOCK GAME START -->

	<!-- Content -->
	<div id="content-article" class="row-fluid rounded backgrey">
		<?php echo $this->form()->openTag($form) ?>
		<?php $i=0;foreach ($form as $groupFieldset): ?>
	        <div class="page" id="<?php echo $groupFieldset->getName()?>">
                <?php foreach ($groupFieldset as $element): ?>
                <?php $question = $this->questions[$i];?>
    			<div class="query-block">
    				<div class="heading"><span>Question <?php echo $i+1; ?></span></div>
    				<div class="orange-dot"></div>
    				<div class="question<?php if($this->channel === 'facebook'): echo ' fb-target'; endif ?>"><?php echo $question->getQuestion();?></div>
    				<?php if($question->getHint()):?>
				    <div class="clue<?php if($this->channel === 'facebook'): echo ' fb-target'; endif ?>">Indice : <?php echo $question->getHint();?></div>
    				<?php endif;?>
    				<?php if($question->getImage()):?>
        				<div class="row-fluid">
        					<div class="span7">
        						<img src="<?php echo $this->basePath($question->getImage())?>" class="rounded" width="300" height="300" border"0" alt="<?php echo $question->getQuestion();?>" />
        					</div>
        					<div class="span5">
        						<div class="row-fluid">
        						<?php if ($element instanceof Zend\Form\Element\Radio): ?>
                                    <?php echo $this->formRadio($element) ?>
                                <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
                                    <?php echo $this->formMultiCheckbox($element);?>
                                <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
                                    <?php echo $this->formTextarea($element); ?>
                                <?php endif;?>
                                <?php //echo $this->formElementErrors($element) ?>
                                <?php if ($element->getMessages()) : echo '<div class="quiz-error">Merci de répondre à la question.</div>'; endif; ?>
                                </div>
        					</div>
        				</div>
    				<?php else:?>
        				<?php if ($element instanceof Zend\Form\Element\Radio): ?>
                            <?php echo $this->formRadio($element) ?>
                        <?php elseif ($element instanceof Zend\Form\Element\MultiCheckbox): ?>
                            <?php echo $this->formMultiCheckbox($element);?>
                        <?php elseif ($element instanceof Zend\Form\Element\Textarea): ?>
                            <?php echo $this->formTextarea($element); ?>
                        <?php endif;?>
                        <?php //echo $this->formElementErrors($element); ?>
						<?php if ($element->getMessages()) : echo '<div class="quiz-error">Merci de répondre à la question.</div>'; endif; ?>
                    <?php endif;?>
                    <?php if($question->getVideo()):?>
                        <div class="video">
        					<iframe width="100%" height="275" src="<?php echo $question->getVideo(); ?>" frameborder="0" allowfullscreen></iframe>
        				</div>
                    <?php endif;?>
    			</div>
    		    <?php ++$i;endforeach;?>
            </div>
		<?php endforeach;?>
		<div class="center">
			<?php if($this->game->getTimer() && $this->game->getTimerDuration() > 0):?>
	            <div class="timer"><?php echo $this->game->getTimerDuration() * 100;?></div>
	        <?php endif;?>
	   </div>
		<div class="center">
            <div class="btn btn-warning previous"><a id="previous" href="#content-article" class="arrow-left"><?php echo $this->translate('Previous questions'); ?></a></div>
            <div class="btn btn-warning next"><a id="next" href="#content-article" class="arrow-right"><?php echo $this->translate('Next questions'); ?></a></div>
	    </div>
	    <div class="center mobile">
            <div class="btn btn-warning end"><button type="submit" name="submitForm" value="" class="arrow-right">Valider mes réponses</button></div>
	    </div>
		<?php echo $this->form()->closeTag() ?>
	</div>
	<p id="reglement"><a href="<?php echo $this->url('frontend/quiz/terms', array('id' => $this->game->getIdentifier()))?>" target="_blank">Règlement</a></p>

</div>
<!-- END GAME QUIZ - FERME QUESTIONS-->

<script type="text/javascript">
jQuery(document).ready(function ($) {
    $('#tabs').tab();
});
</script>
