<?php 
$nextStep = $this->game->nextStep('share');
$nextStep = $nextStep ? $nextStep : 'result'
?>
<?php if(!isset($this->folderUrl)) $this->folderUrl = ""; ?>
<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>
<div class="game-<?php echo $this->game->getClassType(); ?> wrap-game result">
    <h1>
        <?php echo $this->game->getTitle(); ?>
    </h1>
    <?php if($this->game->getClassType() == 'quiz'):?>
        <?php if($this->winner || $this->prediction):?>
            <?php echo $this->partial('playground-game/quiz/partial/winner', array(
                'game'               =>$this->game,
                'userCorrectAnswers' =>$this->userCorrectAnswers,
                'maxCorrectAnswers'  =>$this->maxCorrectAnswers,
                'ratioCorrectAnswers'=>$this->ratioCorrectAnswers,
                'prediction'         =>$this->prediction,
                'flashMessages'      =>$this->flashMessages
            ));?>
        <?php else:?>
            <?php echo $this->partial('playground-game/quiz/partial/looser', array(
                'game'               =>$this->game,
                'userCorrectAnswers' =>$this->userCorrectAnswers,
                'maxCorrectAnswers'  =>$this->maxCorrectAnswers,
                'ratioCorrectAnswers'=>$this->ratioCorrectAnswers,
                'flashMessages'      =>$this->flashMessages
            ));?>
        <?php endif;?>
    
        <?php if($this->userCorrectAnswers < $this->maxCorrectAnswers && $this->game->getVictoryConditions()>0):?>
            <?php echo $this->partial('playground-game/quiz/partial/answers', array(
                'gameCorrectAnswers' =>$this->gameCorrectAnswers
            ));?>
        <?php endif;?>
    <?php endif;?>
    
    <!-- BLOCK GAME START -->
    <div class="block-game game-play <?php if ($this->basePath($this->game->getSecondImage()) == "") echo "no-image"; ?>">
        <img class="img-responsive" src="<?php echo $this->basePath($this->game->getSecondImage()); ?>" />
        <?php if($this->game->getPartner()):?>
            <?php if( ($this->game->getPartner()->getLogo() != '')) : ?>
            <div class="logo-sponsor">
                <img src="<?php echo $this->basePath($this->game->getPartner()->getLogo());?>" alt="<?php echo $this->game->getPartner()->getName();?>" />
            </div>
            <?php endif;?>
        <?php else :?>
            <div class="logo-sponsor">      
                <img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png')?>" alt="logo" />
            </div>
        <?php endif;?>
        <h2 class="col-md-12">
            <?php echo $this->translate('Game offered by'); ?> <?php if($this->game->getPartner()): echo $this->game->getPartner()->getName(); else:?>
                Playground
            <?php endif;?>
        </h2>
    </div>
    <!-- END BLOCK GAME START -->
    
    <!-- BLOCK CONTENT -->
    <div id="content-result" class="content-game clearfix">
        <div class="col-md-1"></div>
        <div class="page col-md-10">
            <h2 class="share-text">
                <?php echo $this->translate('Maximize your chances of winning by inviting your friends to vote for you !'); ?>
                <span><?php echo $this->translate('and earn 250 points per friend you'); ?></span>
            </h2>
            <!-- SPONSOR (parrainer) -->
            <div>
                <?php echo $this->partial('playground-game/partial/result-share', array(
                        'game'          => $this->game,
                        'secretKey'     => $this->secretKey,
                        'socialLinkUrl' => $socialLinkUrl,
                        'form'          => $this->form,
                        'statusMail'    => $statusMail,
                        'gameType'      => $this->game->getClassType()
                )); ?>
                <div class="col-md-12 text-center">
                    <a class="btn btn-default btn-green" href="<?php echo $this->frontendUrl(''. $this->game->getClassType() . '/' . $nextStep, array('id' => $this->game->getIdentifier()));?>">
                        <?php echo $this->translate('Finish'); ?>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <?php echo $this->additional; ?>
    <!-- END SPONSOR (parrainer) -->
</div>
