<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php $game = $this->game;?>
<?php $user = $this->user;?>
<?php $availableGames = $this->availableGames?>

<div class="game-instantwin row-fluid recirculation">
<!-- BOUNCE -->
	<?php echo $this->partial('playground-game/partial/bounce', array(
		'game' => $game,
		'user' => $user,
		'gameType' => 'Cet instant-gagnant',
		'channel' => $this->channel,
		'isSubscriber' => $this->partnerSubscriber($game->getPartner(), $user) )
	);?>
	
	<!-- OTHER GAMES -->
	<?php if($this->channel === ''){?>
	<div class="row-fluid other-games">
		<h2 class="title">
			<?php if($availableGames): ?>
				<?php echo $this->translate('Tentez votre chance avec d\'autres jeux'); ?> Club Playground
			<?php else: ?>
				<?php echo $this->translate('Vous avez joué à tous les jeux'); ?> ! <br/>
				<?php echo $this->translate('Revenez très bientôt'); ?>
			<?php endif; ?>
		</h2>
		
		<?php $this->partialLoop()->setObjectKey('game')?>
		<?php echo $this->partialLoop('playground-game/partial/game.phtml', $availableGames) ?>
	</div>
	<?php } ?>
	
	<!-- RSS FEED -->
	<?php echo $this->partial('playground-game/partial/news-feed', array('rssUrl' => $this->rssUrl)); ?>

</div>