<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<div class="game-lottery row-fluid welcome">
	<h1><?php echo $this->game->getTitle(); ?></h1>

	<!-- BLOCK GAME START -->
    <?php echo $this->partial('playground-game/partial/game-header', array('game'=>$this->game));?>
    <!-- END BLOCK GAME START -->

	<!-- contenu article -->
	<div id="content-article" class="row-fluid rounded backgrey">
		<div class="welcome-block<?php if($this->channel === 'facebook'): echo ' fb-target'; endif ?>"><?php echo $this->game->getWelcomeBlock(); ?></div>
		<?php if($game->isStarted()):?>
		<div class="center">
			<div class="btn btn-warning"<?php if ($this->isCtaActive) { echo ' id="fb-play"'; } ?>>
				<a href="<?php echo $this->url('frontend/lottery/play', array('id' => $this->game->getIdentifier()))?>" class="arrow-right">Participer</a>
			</div>
		</div>
		<?php endif;?>
	</div>
    <p id="conditions"><a href="<?php echo $this->url('frontend/lottery/conditions', array('id' => $this->game->getIdentifier()))?>" target="_blank">Mentions légales</a></p>
	<p id="reglement"><a href="<?php echo $this->url('frontend/lottery/terms', array('id' => $this->game->getIdentifier()))?>" target="_blank">Règlement</a></p>
</div>