<?php
$fm = $this->flashMessenger()->setNamespace('playgroundgame')->getMessages();
if (isset($fm[0]))
{
    print '<span class=>' . $fm[0] . '</span>';
}
?>
<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame'); ?>
<?php $addLink = $this->url('admin/playgroundgame/treasurehunt-step-add', array('gameId' => $this->gameId)); ?>

<ul class="liste-buttons">
	<li class="btn-admin"><a href="<?php echo $addLink;?>"><?php echo $this->translate('Add new step'); ?></a></li>
</ul>

<h1><a href="<?php echo $this->url('admin/playgroundgame/edit-treasurehunt', array('gameId' => $this->gameId)) ?>"><?php echo $this->game->getTitle(); ?></a></h1>

<h3><?php echo $this->translate('Liste des étapes'); ?></h3>

<table class="table">
    <tr>
        <!--<th><?php echo $this->translate('Id'); ?></th>-->
        <th>
        	<?php if($this->filter == 'ASC'): ?>
        	    <a href="<?php echo $this->url('admin/playgroundgame/treasurehunt-step-list', array('gameId' => $this->gameId, 'filter' => 'DESC')); ?>">
        	    	<img src="/images/admin/arrow-down.png" alt="" />
        	    </a>
			<?php else : ?>
				<a href="<?php echo $this->url('admin/playgroundgame/treasurehunt-step-list', array('gameId' => $this->gameId, 'filter' => 'ASC')); ?>">
					<img src="/images/admin/arrow-up.png" alt="" />
				</a>
        	<?php endif; ?>

        <th></th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    <?php foreach ($this->steps as $step): ?>
        <tr>
            <!--<td><?php echo $step->getId() ?></td>-->
            <td></td>
            <?php $editLink   = $this->url('admin/playgroundgame/treasurehunt-step-edit', array('gameId' => $gameId, 'stepId' => $step->getId()));?>
            <?php $deleteLink = $this->url('admin/playgroundgame/treasurehunt-step-remove', array('stepId' => $step->getId()));?>
            <td>ok</td>
            <td>ok</td>
            <td>
                <a href='<?php echo $editLink ?>'><?php echo $this->translate('Edit'); ?></a> | <a href='<?php echo $deleteLink ?>'><?php echo $this->translate('Delete'); ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<ul class="liste-buttons bottom">
	<li class="btn-admin bottom"><a href="<?php echo $addLink;?>"><?php echo $this->translate('Add new step'); ?></a></li>
</ul>

<?php echo $this->paginationControl($this->steps, 'Sliding', 'playground-game/treasure-hunt/pagination_steplist', array('gameId' => $this->gameId, 'filter' => $this->filter)); ?>
