<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<h1><?php echo $this->translate($this->title); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="general">

            <?php echo $this->formHidden($form->get('treasurehunt_id')); ?>

            <?php echo $this->formHidden($form->get('id')); ?>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('hint')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get('hint')); ?>
                    <?php echo $this->formElementErrors($form->get('hint')) ?>
                </div>
                <?php $this->QgCKEditor(
                    'hint',
                        array(
                        	'BasePath' => $this->basePath('js/lib/ckeditor'),
                        	'Width' => "450",
                            'Height' => "100",
                            //'Color' => "#000",
                            /*'Toolbar'=> array(
        	                     array('Bold','Italic','Underline','Link','Unlink'),
                             )*/
							 'Toolbar'=> array(
		                         array('Source','Maximize'),
		                         array('Templates','Styles','Format'),
		                         array('Bold','Italic','Underline','Subscript','Superscript'),
		                         array('NumberedList','BulletedList','Outdent','Indent'),
		                         array('JustifyLeft','JustifyCenter','JustifyRight'),
		                         array('Link','Unlink'),
		                         array('Image','Table')
		                     ),
                        )
                    );
                ?>
            </div>
            
            <div class="control-group">
                <?php echo $this->formLabel($form->get('area')); ?>
                <div class="controls">
                    <?php echo $this->formTextarea($form->get('area')); ?>
                    <?php echo $this->formElementErrors($form->get('area')) ?>
                </div>
            </div>

            <div class="control-group">
                <?php echo $this->formLabel($form->get('timer')); ?>
                <div class="controls"><?php echo $this->formSelect($form->get('timer')); ?></div>
                <?php echo $this->formElementErrors($form->get('timer')) ?>
            </div>
            
            <div class="control-group">
                <?php echo $this->formLabel($form->get('timer_duration')); ?>
                <div class="controls"><?php echo $this->formInput($form->get('timer_duration')); ?></div>
                <?php echo $this->formElementErrors($form->get('timer_duration')) ?>
            </div>
            
            <div class="control-group">
                <?php echo $this->formLabel($form->get('position')); ?>
                <div class="controls"><?php echo $this->formInput($form->get('position')); ?></div>
                <?php echo $this->formElementErrors($form->get('position')) ?>
            </div>

            <?php echo $this->formHidden($form->get('url')); ?>
            <?php echo $this->formHidden($form->get('domain')); ?>
            
            <?php $area = $this->url('admin/playgroundgame/treasure-hunt-areapicker');?>

			<iframe id="area-picker" frameborder="0" width="700" height="800" src="<?php echo $area; ?>"></iframe>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('#tabs').tab();
        $('#occurrence_date').datetimepicker({
        	dateFormat : 'dd/mm/yy'
        });
    });
</script>