<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<h1><?php echo $this->translate($this->title); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
        <li><a href="#mechanics" data-toggle="tab"><?php echo $this->translate('Game Mechanics'); ?></a></li>
        <li><a href="#prizes" data-toggle="tab"><?php echo $this->translate('Lots'); ?></a></li>
        <li><a href="#platform" data-toggle="tab"><?php echo $this->translate('Plateform'); ?></a></li>
        <li><a href="#facebook" data-toggle="tab"><?php echo $this->translate('Facebook'); ?></a></li>
        <li><a href="#embed" data-toggle="tab"><?php echo $this->translate('Embed'); ?></a></li>
        <li><a href="#design" data-toggle="tab"><?php echo $this->translate('Design'); ?></a></li>
        <li><a href="#column" data-toggle="tab"><?php echo $this->translate('Right column'); ?></a></li>
        <li><a href="#share" data-toggle="tab"><?php echo $this->translate('Share'); ?></a></li>
        <li><a href="#welcome_page" data-toggle="tab"><?php echo $this->translate('Welcome block'); ?></a></li>
        <li><a href="#terms_page" data-toggle="tab"><?php echo $this->translate('Payment page'); ?></a></li>
        <li><a href="#conditions_page" data-toggle="tab"><?php echo $this->translate('Legal status'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php echo $this->game_form;?>

        <div class="tab-pane" id="mechanics">
            <div class="row-fluid show-grid">
    
                <div class="span8">
                <ul class="liste-buttons">
                    <li class="btn-admin"><a href="#" onclick="add_game()"><?php echo $this->translate('Add a game'); ?></a></li>
                </ul>

                <div id="game_entry" class="control-group">
                <?php echo $this->formCollection($form->get('missionGames'));?>
                </div>

                <ul class="liste-buttons">
                    <li class="btn-admin"><a href="#" onclick="add_game()"><?php echo $this->translate('Add a game'); ?></a></li>
                </ul>
                </div>
            </div>
            <div class="row-fluid show-grid">
                <div class="span12">
                    <?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
                    <?php echo $this->formButton($form->get('submit')) ?>
                </div>
                <?php echo $this->form()->closeTag() ?>
            </div>

            <script>

                var template = $('#game_entry > fieldset > span');
                var datatemplate = $('#game_entry > fieldset > span').data('template');
                template.data('template', '<fieldset id="games__index__">'+datatemplate+'</fieldset>');

                function add_game() {
                    var currentCount = $('#game_entry select').length;
                    var template = $('#game_entry > fieldset > span').data('template');
                    template = template.replace(/__index__/g, currentCount);
                    $('#game_entry').append(template);
                    $('#game_entry').append('<hr/>');
                    
                    $('#position'+currentCount).val(currentCount);

                    return false;
                }

                $( '#game_entry' ).on('click', '.addCondition', function() {

                        var currentCount = $( this ).parent().children("fieldset").children("input").length;
                        var template = $( this ).parent().children("fieldset").children("span").data('template');
                        template = template.replace(/__index__/g, currentCount);
                        $( this ).parent().children("fieldset").append(template);

                        return false;
                  });

                /*$('#game_entry button').live('click',function(){
                    $(this).parent().parent().empty();
                    return false;
                });*/
            </script>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(event) {
        $('#tabs').tab();
        $('.datepicker').datepicker({
            dateFormat : 'dd/mm/yy'
        });
    });
</script>