<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>

<?php
$form = $this->form;
$form->prepare();
?>

<h1><?php echo $this->translate($this->title); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="general">

            <?php echo $this->formHidden($form->get('instant_win_id')); ?>


            <div class="label-input">
                <?php echo $this->formLabel($form->get('file')); ?>
	            <?php echo $this->formFile($form->get('file')); ?>
	            <?php echo $this->formElementErrors($form->get('file')); ?>
	        </div>
	        <div class="label-input">
	            <?php echo $this->formLabel($form->get('active')); ?>
	            <?php echo $this->formSelect($form->get('active')); ?>
	            <?php echo $this->formElementErrors($form->get('active')) ?>
	        </div>
	        <div class="label-input">
		        <?php echo $this->formLabel($form->get('prize')); ?>
		        <?php echo $this->formSelect($form->get('prize')); ?>
		        <?php echo $this->formElementErrors($form->get('prize')) ?>
			</div>
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>