<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundgame');// Pour le texte ?>
<?php
$form = $this->form;
$form->prepare();
?>

<div class="return"><a href="<?php echo $this->url('admin/playgroundgame/list');?>"><?php echo $this->translate('Retour'); ?></a></div>

<h1><?php echo $this->translate($this->title); ?></h1>

<?php echo $this->form()->openTag($form) ?>
<?php $form->get('submit')->setLabel($this->translate('Validate')); ?>
<?php echo $this->formButton($form->get('submit')) ?>

<div id="content" class="tabbable tabs-left">
    <ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
        <li class="active"><a href="#general" data-toggle="tab"><?php echo $this->translate('General'); ?></a></li>
        <li><a href="#mechanics" data-toggle="tab"><?php echo $this->translate('Mécanique du jeu'); ?></a></li>
        <li><a href="#prizes" data-toggle="tab"><?php echo $this->translate('Lots'); ?></a></li>
        <li><a href="#platform" data-toggle="tab"><?php echo $this->translate('Plateforme'); ?></a></li>
        <li><a href="#facebook" data-toggle="tab"><?php echo $this->translate('Facebook'); ?></a></li>
        <li><a href="#design" data-toggle="tab"><?php echo $this->translate('Design'); ?></a></li>
        <li><a href="#column" data-toggle="tab"><?php echo $this->translate('Colonne de droite'); ?></a></li>
        <li><a href="#share" data-toggle="tab"><?php echo $this->translate('Partage'); ?></a></li>
        <li><a href="#welcome_page" data-toggle="tab"><?php echo $this->translate('Bloc de bienvenue'); ?></a></li>
        <li><a href="#terms_page" data-toggle="tab"><?php echo $this->translate('Page de règlement'); ?></a></li>
        <li><a href="#conditions_page" data-toggle="tab"><?php echo $this->translate('Mentions légales'); ?></a></li>
    </ul>
    <div id="my-tab-content" class="tab-content">
        <?php echo $this->game_form;?>

        <div class="tab-pane" id="mechanics">
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('drawAuto')); ?>
	            <?php echo $this->formSelect($form->get('drawAuto')); ?>
	            <?php echo $this->formElementErrors($form->get('drawAuto')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('winners')); ?>
	            <?php echo $this->formInput($form->get('winners')); ?>
	            <?php echo $this->formElementErrors($form->get('winners')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('substitutes')); ?>
	            <?php echo $this->formInput($form->get('substitutes')); ?>
	            <?php echo $this->formElementErrors($form->get('substitutes')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('timer')); ?>
	            <div class="radio">
		            <?php echo $this->formRadio($form->get('timer')); ?>
		            <?php echo $this->formElementErrors($form->get('timer')) ?>
		        </div>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('timerDuration')); ?>
	            <?php echo $this->formInput($form->get('timerDuration')); ?>
	            <?php echo $this->formElementErrors($form->get('timerDuration')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('questionGrouping')); ?>
	            <?php echo $this->formInput($form->get('questionGrouping')); ?>
	            <?php echo $this->formElementErrors($form->get('questionGrouping')) ?>
			</div>
			<div class="label-input">
	            <?php echo $this->formLabel($form->get('victoryConditions')); ?>
	            <?php echo $this->formInput($form->get('victoryConditions')); ?>
	            <?php echo $this->formElementErrors($form->get('victoryConditions')) ?>
	        </div>
            <!-- div id="slider" style="width:250px"></div-->
        </div>
    </div>
</div>
<?php echo $this->form()->closeTag() ?>

<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $('#tabs').tab();
        $('.datepicker').datepicker({
            dateFormat : 'dd/mm/yy'
        });
       /* $( "#slider" ).slider({
            min: 0,
            max: 100,
            step: 5,
            slide: function( event, ui ) {
              $( "#victoryConditions" ).val( ui.value );
            }
          });
         $( "#victoryConditions" ).val( $( "#slider" ).slider( "value" ) );*/
    });
</script>