<?php if ($game->getStartDate() && $game->getEndDate()):?>
    <?php $play =  'Jouez du ' . strftime("%d %B", $game->getStartDate()->format('U')) . ' au ' . strftime("%d %B", $game->getEndDate()->format('U')) . ' avec'; ?>
<?php elseif ($game->getStartDate()):?>
    <?php $play =  'Jouez à partir du ' . strftime("%d %B", $game->getStartDate()->format('U')) . ' avec';?>
<?php elseif ($game->getEndDate()):?>
    <?php $play =  'Jouez jusqu\'au ' . strftime("%d %B", $game->getEndDate()->format('U')) . ' avec';?>
<?php else:?>
    <?php $play =  'Jouez avec';?>
<?php endif; ?>
<div class="item <?php if(isset($first)): ?>active<?php $first=false;endif; ?> ">
    <div class="span12">
        <div class="img-content">
            <a href="<?php echo $this->url('frontend/' . $game->getClassType()) . '/' . $game->getIdentifier(); ?>"><img src="<?php echo $this->basePath($game->getMainImage());?>" border="0" alt="<?php echo $game->getTitle(); ?>" /></a>
            <div class="dark-overlay row-fluid">
                <h1 class="title-promo"><a href="<?php echo $this->url('frontend/' . $game->getClassType()) . '/' . $game->getIdentifier(); ?>"><?php echo $game->getTitle(); ?></a></h1>
                <?php if($game->isStarted()):?>
                	<div class="button-wrap">
                    	<div class="btn btn-warning"><a href="<?php echo $this->url('frontend/' . $game->getClassType()) . '/' . $game->getIdentifier(); ?>" class="arrow-right-big">Jouer</a></div>
                    </div>
                <?php elseif($game->isOpen() && !$game->isFinished() ):?>
                	<div class="button-wrap">
                    	<div class="btn btn-warning"><a href="<?php echo $this->url('frontend/' . $game->getClassType()) . '/' . $game->getIdentifier(); ?>" class="arrow-right-big">Bientôt</a></div>
                    </div>
                <?php endif;?>
            </div>

        </div>
        <div class="promo-infos">
            <div class="<?php echo $game->getClassType(); ?>"><?php echo $this->translate($game->getClassType()); ?> : <?php echo $play;?></div>
            <div class="logo-partner">
            	<?php if($game->getPartner()):?>
            		<?php if($game->getPartner()->getSmallLogo()) : ?>
            			<img src="<?php echo $this->basePath($game->getPartner()->getSmallLogo());?>" border="0" alt="<?php echo $game->getPartner()->getName();?>" />
            		<?php else:?>
    					<span><?php echo $game->getPartner()->getName();?></span>
    				<?php endif;?>
            	<?php else :?>
            		<img src="<?php echo $this->frontendAssetPath('images/common/logo-game-start.png');?>" height="33" border="0" alt="Logo" />
            	<?php endif;?>
            </div>

            <?php if(!$game->isFinished()):?>
            	<?php echo $this->partial('playground-game/partial/share.phtml', array( 'color' => 'dark','game'=>$this->game, 'url'=>$this->url('frontend/' . $game->getClassType(), array('id' => $this->game->getIdentifier()), array('force_canonical' => true))));?>
            <?php endif; ?>
        </div>
        <?php if($game->isFinished()):?>
    	    <div class="stamp"><img src="images/common/stamp-termine.png" width="156" height="123" borde="0" alt="jeu terminé" /></div>
    	<?php endif;?>
        <div class="shadow-toppromo"></div>
    </div>
</div>
