<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
    <head>
        <?php //echo $this->head();?>
    </head>
    <body class="<?php echo $this->bodyCss ?>">
		<div id="container">
		    <div id="fb-root"></div>
            <div id="content" class="row-fluid">
                <div id="random-game" class="shadow">
                	<div class="row-fluid">
                		<div class="span8">
                			<?php echo $this->content; ?>
                		</div>
                		<?php echo $this->column_right; ?>
                	</div>
                </div>
                <?php //echo $this->footer(array('channel' => $this->channel));?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
