<?php echo $this->doctype(); ?>
<?php
$children = $this->viewModel()
    ->getCurrent()
    ->getChildren();

$ourView  = $children[0];
?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
    <head>
        <?php //echo $this->head();?>
    </head>
    <body>
		<div id="container">
		    <div id="fb-root"></div>
            <div id="content" class="row-fluid">
                <!-- <div id="ad-left"><img src="<?php //echo $this->frontendAssetPath('images/adserving/adserving-left.jpg')?>" border="0" /></div> -->
                <!-- <div id="ad-right"><img src="<?php //echo $this->frontendAssetPath('images/adserving/adserving-right.jpg')?>" border="0" /></div> -->
                <?php //echo $this->header(array('channel' => $this->channel));?>
                <!-- <div id="ad-mega-banner"><img src="<?php //echo $this->frontendAssetPath('images/adserving/adserving-mega-banner.jpg')?>" border="0" /></div> -->
                <?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) : ?>
                <ul class="flashMessages">
                    <?php foreach ($ourView->flashMessages as $fMessage) : ?>
                    <li><?php echo $fMessage; ?></li>
                    <?php endforeach; ?>
                </ul>
                <?php endif; ?>
                <div id="random-game" class="shadow">
                	<div class="row-fluid">
                		<div class="span8">
                			<?php echo $this->content; ?>
                		</div>
                		<?php echo $this->column_right; ?>
                	</div>
                </div>
                <?php //echo $this->footer(array('channel' => $this->channel));?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
