<?php echo $this->doctype(); ?>
<?php $this->plugin('translate')->setTranslatorTextDomain('default');// Pour le texte ?>    
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr">
    <head></head>
    <body class="<?php echo $this->bodyCss ?>">
        <div id="container">
            <div id="fb-root"></div>
    		<div id="content" class="row-fluid">
                <div id="containerpage">
                	<?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
